GET http://127.0.0.1:8000/todo/99

###
POST http://127.0.0.1:8000/todo 
content-Type: application/json; charset=UTF-8

{
    "id": 1,
    "item": "Hello1"
}

###
PUT http://127.0.0.1:8000/event/edit/1
content-Type: application/json; charset=UTF-8

{
    "title": "UPDATED TITLE11"
}

###
DELETE http://127.0.0.1:8000/todo/99


###
curl --request GET
    --url http://127.0.0.1:8000/event

###
curl --request POST 
    --url http://127.0.0.1:8000/event/new
    --header 'content-type: application/json'
    --data '{
        "title": "title 2",
        "image": "image 2",
        "description": "description 2",
        "location": "location 2",
        "tags": ["tag 2_1","tag 2_2","tag 2_3"]
    }'


###
curl --request POST 
    --url http://127.0.0.1:8000/user/signup
    --header 'content-type: application/json'
    --data '{
        "email": "NotEmailType",
        "username": "username 2",
        "password": "password1!"
    }'

###
curl --request POST 
    --url http://127.0.0.1:8000/user/signin
    --header 'content-type: application/json'
    --data '{
        "email": "email1@yescnc.co.kr",        
        "password": "wrongpassword!"
    }'

###
curl --request PUT 
    --url http://127.0.0.1:8000/event/1
    --header 'accept: application/json'
    --header 'content-type: application/json'   
    --data '{
        "title": "updated title 1"
    }'
    
###
curl --request DELETE 
    --url http://127.0.0.1:8000/event/2
    