POST http://127.0.0.1:8000/todo 

{
    "id": 2,
    "item": "Hello"
}

###
GET http://127.0.0.1:8000/todo

###
curl --request POST 
    --url http://127.0.0.1:8000/todo 
    --header 'content-type: application/json'
    --data '{
        "id": 3,         
        "item": "Third Todo!"
        }'

###
curl --request GET
    --url http://127.0.0.1:8000/todo
    
