GET http://127.0.0.1:8000/todo/99

###
POST http://127.0.0.1:8000/todo 
content-Type: application/json; charset=UTF-8

{
    "id": 1,
    "item": "Hello1"
}

###
PUT http://127.0.0.1:8000/event/64a258517d60e990212150ed  
content-Type: application/json; charset=UTF-8
Accept: application/json

{
    "location": "UPDATED TITLE11"
}

###
DELETE http://127.0.0.1:8000/todo/99


###
curl --request GET
    --url http://127.0.0.1:8000/user/signin

###
curl --request POST 
    --url http://127.0.0.1:8000/user/signin
    --header 'content-type: application/json'
    --data '{        
        "email": "jhlee@yescnc.co.kr",
        "username": "soronprfbs",
        "password": "password1!"
    }'

###
curl -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      -request POST 
    --url http://127.0.0.1:8000/user/signin
    --header 'content-type: application/x-www-form-urlencoded'
    --header 'accept: application/json'
    --data 'grant_type=&username=jhlee%40yescnc.co.kr&password=exemplary&scope=&client_id=&client_secret='


###
curl --request PUT 
    --url http://127.0.0.1:8000/event/64a258517d60e990212150ed    
    --header 'content-type: application/json'   
    --data '{
        "location": "Hybrid"
    }'
    
###
curl --request DELETE 
    --url http://127.0.0.1:8000/event/64a258517d60e990212150ed
    