GET http://127.0.0.1:8000/todo/99

###
POST http://127.0.0.1:8000/todo 
content-Type: application/json; charset=UTF-8

{
    "id": 1,
    "item": "Hello1"
}

###
PUT http://127.0.0.1:8000/event/64a258517d60e990212150ed  
content-Type: application/json; charset=UTF-8
Accept: application/json

{
    "location": "UPDATED TITLE11"
}

###
DELETE http://127.0.0.1:8000/todo/99


###
curl --request GET
    --url http://127.0.0.1:8000/event/

###
curl -X 'POST' \
    'http://127.0.0.1:8000/user/signup' \
    -H 'content-type: application/json' \
    -d '{
    "email": "guest@yescnc.co.kr",
    "password": "guestpwd!"
}'

###
curl -X 'POST' \
    'http://127.0.0.1:8000/user/signin' \
    -H 'content-type: application/x-www-form-urlencoded' \
    -d 'grant_type=&username=guest%40yescnc.co.kr&password=guestpwd!&scope=&client_id=&client_secret='

###
curl -X 'POST' \
    'http://127.0.0.1:8000/event/new' \
    -H 'accept: application/json'  \
    -H 'Content-Type: application/json' \
    -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiZ3Vlc3RAeWVzY25jLmNvLmtyIiwiZXhwaXJlcyI6MTY4OTIzNjgxOS41NzEwNjY2fQ.2aqWMU83m7WRmJxsPD6tEziaoKlg4wIbOgQbNUuskwc' \
    -d '{
        "title": "게스트 이벤트 타이틀 1",
        "image": "http://게스트이미지경로 1",
        "description": "게스트 이벤트에 대한 설명 1",
        "location": "게스트 이벤트 위치 1",
        "tags": [
            "게스트 태그 1",
            "게스트 태그 2",
            "게스트 태그 3"
        ]
}'

###
curl -X 'PUT' \
    'http://127.0.0.1:8000/event/1' \
    -H 'accept: application/json'  \
    -H 'Content-Type: application/json' \
    -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiamhsZWVAeWVzY25jLmNvLmtyIiwiZXhwaXJlcyI6MTY4OTMxMjg2NC40OTk4NjZ9.Iqrt-afgwfGorbuebQAqV-E5ZJXijAcFYgm7OmRCgCU' \
    -d '{
        "title": "PUT요청으로 변경된 타이틀 1"       
}'

###
curl -X 'POST' \
  'http://localhost:8000/user/signin' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'grant_type=&username=jhlee%40yescnc.co.kr&password=pwd123!&scope=&client_id=&client_secret='

###
curl -X DELETE \
    'http://127.0.0.1:8000/event/2' \
    -H 'accept: application/json' \
    -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiZ3Vlc3RAeWVzY25jLmNvLmtyIiwiZXhwaXJlcyI6MTY4OTIzNzA1My4wMjkzMDY3fQ.LTGh10QMlAQ9k7-yOW0qq2y6kSBuCo1FZhfqbERHlPo' \
    -H 'content-type: application/json' \    
    
###
curl --request DELETE 
    --url http://127.0.0.1:8000/event/64a258517d60e990212150ed
    